---
environment: infra-test
accesses_real_data: false
core_address_space: 10.64.0.0/22
private_dns_zones_rg: rg-bootstrap-uclh-ci-dev

transform:
  spark_version: 3.4
  repositories:
    - url: https://github.com/UCLH-Foundry/FlowEHR-Data-Pot
  datalake:
    zones:
      - Bronze
      - Silver
      - Gold
  spark_config:
    - key: spark.databricks.cluster.profile
      value: singleNode
    - key: spark.master
      value: local[*]
  databricks_libraries:
    pypi:
      - opencensus-ext-azure==1.1.9
      - opencensus-ext-logging==0.1.1

serve:
  github_owner: UCLH-FlowEHR-TestBed
  github_app_id: 309047
  github_app_installation_id: 35581991
