---
environment: ml-dev
core_address_space: 10.64.8.0/22
accesses_real_data: true

data_source_connections:
  - emap:
    name: star
    peering:
      virtual_network_name: vnet-data-sources-ds-uclhflowehr-prod
      resource_group_name: rg-ds-uclhflowehr-prod
      dns_zones:
        - privatelink.postgres.database.azure.com
    fqdn: psqlserver-ds-uclhflowehr-prod.postgres.database.azure.com
    database: emap
    username: flowehr
    password: ${EMAP_STAR_CONSUMER_PASSWORD}

monitoring:
  alert_recipients:
    - name: David Ramlakhan
      email: d.ramlakhan@nhs.net
    - name: Richard Clarke
      email: richard.clarke14@nhs.net
  network_watcher:
    name: NetworkWatcher_uksouth
    resource_group_name: NetworkWatcherRG
