---
environment: test
accesses_real_data: false
core_address_space: 10.60.0.0/22
private_dns_zones_rg: rg-mric-landing-test

data_source_connections:
  - rio_tre:
    name: rio-tre
    peering:  # Optional
      virtual_network_name: vnet-landing-mric-landing-test
      resource_group_name: rg-mric-landing-test
    fqdn: sql-server-mriclandingtest.database.windows.net
    database: rio_tre
    username: ce5de5ba-b69b-4067-a68f-8c20ba43be53
    password: ${DATABRICKS_READER}

transform:
  spark_version: 3.4
  repositories:
    - url: https://github.com/M-RIC-TRE/mric-pipelines.git
  datalake:
    zones:
      - Bronze
      - Silver
      - Gold
  spark_config:
    spark.databricks.delta.properties.defaults.enableChangeDataFeed: "true"
  databricks_libraries:
    pypi:
      - package: opencensus-ext-azure==1.1.9
      - package: opencensus-ext-logging==0.1.1
      - package: presidio-analyzer==2.2.33
      - package: presidio-anonymizer==2.2.33
      - package: synapseml==0.11.2
  databricks_cluster:
    autotermination_minutes: 10
    autoscale:
      min_workers: 1
      max_workers: 8
    init_scripts:
      - ../../transform/pipelines/mric-pipelines/pipelines/rio_pipeline/scripts/init_script.sh
  databricks_secrets:
    cognitive_services_key: ${COGNITIVE_SERVICES_KEY}
    cognitive_services_location: uksouth
