---
environment: test
accesses_real_data: false
core_address_space: 10.60.0.0/22
private_dns_zones_rg: rg-bootstrap-mricboot-dev

transform:
  spark_version: 3.4
  repositories:
    - url: git@github.com:M-RIC-TRE/mric-pipelines.git
  datalake:
    zones:
      - Bronze
      - Silver
      - Gold
  spark_config:
    spark.databricks.delta.properties.defaults.enableChangeDataFeed: "true"
  databricks_libraries:
    pypi:
      - package: opencensus-ext-azure==1.1.9
      - package: opencensus-ext-logging==0.1.1
      - package: presidio-analyzer==2.2.33
      - package: presidio-anonymizer==2.2.33
  databricks_cluster:
    autotermination_minutes: 10
    autoscale:
      min_workers: 1
      max_workers: 8
