# TODO:
# These values need to be checked in as they are the same for local env and for CI / CD.
# There is a story to improve this: https://github.com/UCLH-Foundry/FlowEHR/issues/42
# As part of this story, this file will likely disappear.
---
spark_version: 3.3.0
repositories:
 - git@github.com:tanya-borisova/test-data-pipeline.git
 - git@github.com:UCLH-Foundry/FlowEHR-Data-Forge.git
