#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
name: Clean state

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: The environment where resources have been deployed to
      devcontainer_name:
        type: string
        required: false
        description: The devcontainer image name to delete from ACR
        default: flowehr/devcontainer
      suffix_override:
        type: string
        required: false
        description: An override for the naming suffix
    secrets:
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true

jobs:
  clean:
    name: Clean devcontainer & TF state
    runs-on: [self-hosted, "${{ vars.CI_GITHUB_RUNNER_LABEL }}"]
    environment: ${{ inputs.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      - name: Delete TF state
        run: |
          az storage blob delete-batch \
            --account-name "${{ vars.CI_STORAGE_ACCOUNT }}" \
            --source tfstate \
            --pattern "flowehr/${{ (inputs.suffix_override != '' && inputs.suffix_override) || inputs.environment }}/*" \
            --auth-mode login
      - name: Untag devcontainer image
        run: |
          az acr repository untag \
            --name "${{ vars.CI_CONTAINER_REGISTRY }}" \
            --image "${{ inputs.devcontainer_name }}:${{ (inputs.suffix_override != '' && inputs.suffix_override) || inputs.environment }}"
