#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
---
name: PR Checks

on:
  pull_request:

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.workflow }}-${{ github.head_ref }}-validate"
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        name: Cache tf plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.4.4

      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.44.1

      - name: Setup Terragrunt
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.42.8/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate terraform
        run: |
          (cd bootstrap/shared \
            && (cd management && terraform init -backend=false) \
            && (cd naming && terraform init -backend=false) \
          )
          terragrunt run-all validate --terragrunt-no-auto-init

      - name: Pre-commit linting
        uses: pre-commit/action@v3.0.0
